# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  name: 'test1'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: ScreenResolutionUtility@1
  inputs:
    displaySettings: 'specific'
    width: '1280'
    height: '1024'
- task: CmdLine@2
  inputs:
    script: |
      start ffmpeg -y -rtbufsize 200M -f gdigrab -framerate 15 -probesize 10M -draw_mouse 1 -i desktop -c:v libx264 -r 30 -preset ultrafast -tune zerolatency -crf 25 -pix_fmt yuv420p $(Agent.TempDirectory)\\recording.mp4
      dir
      timeout 10
      taskkill /im ffmpeg.exe
  condition: succeeded()
  displayName: 'GFriend Runner Execution'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Agent.TempDirectory)'
    artifact: 'ado_gfriend_resutl_$(Agent.ID)'
    publishLocation: 'pipeline'
  displayName: 'Publish GF data result'
  condition: always()