# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

variables:
- name: vm_count 
  value: 5

stages:
- stage: Terraform
  jobs:
  - job: J1
    workspace:
      clean: all
    steps:
      - bash: |
          echo "id_1=1"
          echo "##vso[task.setvariable variable=t1;isOutput=true]${i}"
  - job: T2
    dependsOn: J1
    steps:
      - bash: |
          echo ${{ variables.vm_count}}
          echo ${{ variables.t1}}
        