# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
    - repository: Ecosystem-Trunk
      type: githubenterprise
      name: Ecosystem-Trunk/ET-Catalogue
      endpoint: GHE_Partners
      ref: dev

trigger:
- none

variables:
  - name: ADO_GFRIEND_HOME
    value: C:\\agent\\_work\\_tool\\gfriend\\
pool:
  name: 'test1'

steps:
- checkout: self
- checkout: Ecosystem-Trunk
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      choco install GoogleChrome --ignore-checksums
      choco install selenium
      choco install selenium-all-drivers
  displayName: 'Chrome and Selenium Installation'

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: ScreenResolutionUtility@1
  inputs:
    displaySettings: 'specific'
    width: '1280'
    height: '1024'
- task: InstallPython@1
  inputs:
    version: 'python'
    #Note
    # install pip as part of the dependencies because otherwise we get a warning which causes ADO to fail due to pip not being the latest version
    dependencies: 'pip requests'
  displayName: 'Python Installation'
- script: |
    python --version
  displayName: 'Python Version'

- script: |
    set
  displayName: 'Env Variables'
  condition: always()

- powershell: |
    Write-Host loadtesthpsmat+$(Agent.MachineName)$(Build.BuildNumber)$(Build.BuildId)@gmail.com
  displayName: 'Signup Username account'  
- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: |
      import requests
      import zipfile
      gfriend_location_url = "https://8v0mj43oxb.execute-api.ap-northeast-2.amazonaws.com/gfriend/binary/gfriend"
      r = requests.get(gfriend_location_url, allow_redirects=True)
      open('gfriend', 'wb').write(r.content)
      with zipfile.ZipFile('gfriend', 'r') as zip_ref:
          zip_ref.extractall('$(ADO_GFRIEND_HOME)')
  condition: succeeded()
  displayName: 'GFriend Installation'
- task: CmdLine@2
  inputs:
    script: |
      start ffmpeg -y -rtbufsize 200M -f gdigrab -framerate 15 -probesize 10M -draw_mouse 1 -i desktop -c:v libx264 -r 30 -preset ultrafast -tune zerolatency -crf 25 -pix_fmt yuv420p $(Agent.TempDirectory)\\recording.mp4
      $(ADO_GFRIEND_HOME)\\GF_Runner.exe -i 15.86.1.35 -t ET-Catalogue\Integration\hpid\ui_HPSmart.txt -c HP_ID_SignUp_Stage -o $(Agent.TempDirectory)
      taskkill /im ffmpeg.exe
  condition: succeeded()
  displayName: 'GFriend Runner Execution'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Agent.TempDirectory)'
    artifact: 'ado_gfriend_resutl_$(Agent.ID)'
    publishLocation: 'pipeline'
  displayName: 'Publish GF data result'
  condition: always()